### PR TITLE
fix!: Declare webpack as the peer dependency

### PR DESCRIPTION
**Pull request by pan93412**
<https://classic.yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies>

Workaround of a Yarn Berry behavior, which makes the Webpack instance of `pino-webpack-plugin` is different to one of the project: <https://github.com/yarnpkg/berry/issues/2401>.

```
/Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-76a0caa910/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143
                        throw new TypeError(
                        ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (/Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-76a0caa910/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:143:10)
    at /Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-76a0caa910/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/javascript/CommonJsChunkFormatPlugin.js:43:19
    at Hook.eval [as call] (eval at create (/Volumes/Dev/OSS/unm-js/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Volumes/Dev/OSS/unm-js/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-da9352bce3/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/Compiler.js:1121:30)
    at /Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-da9352bce3/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/Compiler.js:1166:29
    at Hook.eval [as callAsync] (eval at create (/Volumes/Dev/OSS/unm-js/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Volumes/Dev/OSS/unm-js/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-da9352bce3/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/Compiler.js:1161:28)
    at /Volumes/Dev/OSS/unm-js/.yarn/__virtual__/webpack-virtual-da9352bce3/0/cache/webpack-npm-5.75.0-ebca50e2e7-2bcc5f3c19.zip/node_modules/webpack/lib/Compiler.js:524:12

Node.js v19.1.0
```

[Other projects also do this.](https://github.com/jantimon/html-webpack-plugin/blob/main/package.json#L59)

### CODE REVIEW

**Comment by ShogunPanda** [comment]
@pan93412 The change looks legit to me. Can you fix the workflow files so that webpack get installed in GitHub actions (and therefore the CI does not fail)?

**Comment by pan93412** [comment]
https://github.com/pan93412/pino-webpack-plugin/actions/runs/4090313789 It seems working! cc @ShogunPanda

**Review by ShogunPanda — APPROVED** [review]
LGTM!

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
