### PR TITLE
fix: Make sure transports are required. Fixes #43.

### LINKED ISSUE #43: Transport js file is not generated unless I include a dummy import to the transport module
With the following configuration:
<details><summary><code>index.ts</code></summary>

```ts
import pino from 'pino';
// import 'pino-pretty';

const logger = pino({level: 'info'}, pino.multistream([pino.transport({target: 'pino-pretty'})]));
logger.info("Test");
```
</details>

<details><summary><code>webpack.config.ts</code></summary>
/// <reference path="./pino-webpack-plugin.d.ts" />

import webpack from 'webpack';
import { PinoWebpackPlugin } from 'pino-webpack-plugin';

const config: webpack.Configuration = {
    target: 'node',
    mode: 'development',
    devtool: 'eval-source-map',

    entry: {
        index: './src/index.ts',
    },

    resolve: {
        extensions: ['.ts', '.js']
    },

    output: {
        library: {
            type: 'commonjs2'
        },
    },

    module: {
        rules: [
          {
            test: /\.ts$/,
            exclude: /node_modules/,
            use: 'ts-loader',
          },
        ],
    },

    plugins: [
        new PinoWebpackPlugin({
            transports: ['pino-pretty']
        })
    ]
};

export default config;
</details>

<details><summary><code>tsconfig.json</code></summary>
{
    "extends": "@tsconfig/node16/tsconfig.json",
    "include": ["src/**/*"],
    "compilerOptions": {
        "outDir": "dist",
        "sourceMap": true
    }
}
</details>

Unless I uncomment the line in `index.ts` that imports `pino-pretty`, no `pino-pretty.js` file will be generated. This is not documented in the README and I believe shouldn't be required given we supply the plugin with a list of transports it should bundle.

### PR DESCRIPTION
**Pull request by ShogunPanda**
Fixes #43.

### CODE REVIEW

**Comment by simoneb** [comment]
Shall we have a test? Sound like a fairly simple use case to test

**Comment by ShogunPanda** [comment]
@simoneb Done! ^^

**Comment by simoneb** [comment]
@ShogunPanda booom 💥

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by ShogunPanda** [comment]
Can I merge this?

**Review by simoneb — APPROVED** [review]

**Pull request merged**
